version: '2'
services:
  web:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3002:80
    links:
      - dbhost

  dbhost:
    image: percona:5.6.26
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=symfony
    volumes:
        - ./db/mysql:/var/lib/mysql